# Generated by Django 5.2 on 2025-05-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
