# Generated by Django 5.2 on 2025-05-07 16:58

import uuid
from django.db import migrations, models

def generate_uuids(apps, schema_editor):
    Quiz = apps.get_model('teacher_space', 'Quiz')
    for quiz in Quiz.objects.all():
        quiz.share_token = uuid.uuid4()
        quiz.save(update_fields=['share_token'])

class Migration(migrations.Migration):

    dependencies = [
        ('teacher_space', '0004_quiz_is_generated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='access_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='current_participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='last_shared',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        # Étape 1: Ajouter le champ sans unique=True
        migrations.AddField(
            model_name='quiz',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Étape 2: Remplir les valeurs
        migrations.RunPython(
            generate_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        # Étape 3: Ajouter la contrainte unique
        migrations.AlterField(
            model_name='quiz',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]