# Generated by Django 5.2 on 2025-05-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_space', '0005_alter_quiz_options_quiz_access_restricted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='display_name',
            field=models.CharField(default='default-subject', max_length=255),
            preserve_default=False,
        ),
    ]
