# Generated by Django 5.2 on 2025-05-16 19:53

from django.db import migrations

def fix_names(apps, schema_editor):
    Module = apps.get_model('teacher_space', 'Module')
    for module in Module.objects.all():
        if not hasattr(module, 'display_name'):
            module.display_name = module.name
            module.name = module.name.lower().strip()
            module.save()

class Migration(migrations.Migration):
    dependencies = [
        ('teacher_space', '0006_module_display_name'),
    ]
    
    operations = [
        migrations.RunPython(fix_names),
    ]