# Generated by Django 5.2 on 2025-05-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
