# Generated by Django 5.2 on 2025-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_space', '0002_module_normalized_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='normalized_name',
            field=models.CharField(default='default-subject-temp', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
