# Generated by Django 5.2 on 2025-05-29 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_space', '0003_alter_module_normalized_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='normalized_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('normalized_name', 'student'), name='unique_module_per_student'),
        ),
    ]
