# Generated by Django 5.2 on 2025-06-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_space', '0006_quizresult_answers_alter_quizresult_quiz_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            CREATE TABLE IF NOT EXISTS student_space_sharedquizaccess (
                id INT AUTO_INCREMENT PRIMARY KEY,
                quiz_id INT NOT NULL,
                student_id INT NOT NULL,
                is_used BOOLEAN NOT NULL DEFAULT FALSE,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (quiz_id) REFERENCES teacher_space_quiz(id),
                FOREIGN KEY (student_id) REFERENCES auth_user(id),
                UNIQUE (quiz_id, student_id))
            ''',
            reverse_sql='DROP TABLE student_space_sharedquizaccess'
        ),
        migrations.RunSQL(
            sql='''
            CREATE TABLE IF NOT EXISTS student_space_sharedquizresult (
                id INT AUTO_INCREMENT PRIMARY KEY,
                shared_quiz_id INT NOT NULL,
                student_id INT NOT NULL,
                score INT NOT NULL,
                total_questions INT NOT NULL,
                answers JSON NOT NULL,
                submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (shared_quiz_id) REFERENCES student_space_sharedquizaccess(id),
                FOREIGN KEY (student_id) REFERENCES auth_user(id)
            )
            ''',
            reverse_sql='DROP TABLE student_space_sharedquizresult'
        )
    ]
